main/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name="home"),
]

main/main/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('client/',include('client.urls')),
    path('manager/',include('manager.urls')),
    path('account/',include('account.urls')),
]

main/manager/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.manager,name='manager'),
    path('profile/',views.profile,name='profile_manager'),
    path('create-room/',views.createRoom,name='create_room'),
    path('room-delete/<str:pk>/', views.deleteRoom, name='delete_room'),
    path('create-room/time-slot/<str:pk>/',views.addTimeSlot,name='time_slot'),
    path('advance_days/', views.editAdvanceDays, name="advance_days"),
    path('room/<str:pk1>/delete-time-slot/<str:pk2>', views.deleteTimeSlot, name="delete_slot"),
    path('view-bookings/',views.bookingHistory,name="bookings")
]

main/manager/models.py
from django.db import models
from account.models import CustomUser
import uuid

class Rooms(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    room_owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    room_name = models.CharField(max_length=10, null=False)

    class Meta:
        unique_together = ('room_owner', 'room_name')

    def __str__(self):
        return self.room_name

    def __unicode__(self):
        pass

class TimeSlot(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    room_id = models.ForeignKey(Rooms, on_delete=models.CASCADE)
    slot_owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    start_time = models.TimeField(null=False)
    end_time = models.TimeField(null=False)

    class Meta:
        unique_together = ('room_id','start_time','end_time')

    def __str__(self):
        return str(self.start_time) + "-" + str(self.end_time)

class AdvanceBooking(models.Model):
    manager_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="room_manager_id")
    no_of_days = models.IntegerField(null=False, default=15, blank=False)

    def __str__(self):
        return str(self.manager_id) + " " + str(self.no_of_days)

main/manager/forms.py
from django.forms import ModelForm
from .models import Rooms,TimeSlot


class RoomForm(ModelForm):
    class Meta:
        model = Rooms
        fields = ('room_name', )

class TimeSlotForm(ModelForm):
    class Meta:
        model = TimeSlot
        fields = ('start_time', 'end_time',)

main/manager/views.py
from django.shortcuts import render,redirect
from .models import Rooms,TimeSlot,AdvanceBooking
from .forms import RoomForm,TimeSlotForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from manager.decorators import role_required
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from client.models import TimeSlotBook,TimeSlotCancel
from account.models import CustomUser

@login_required
def profile(request):
    if request.method=="POST":
        user = CustomUser.objects.get(username=request.POST.get('username'))
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.email = request.POST.get('email')
        user.phone = request.POST.get('phone')
        # print((request.POST.get('username')))
        user.save()
        messages.success(request,"Profile Updated")
        return redirect('profile_manager')
    return render(request,'profile.html')

@login_required
@role_required(allowed=['manager'])
def manager(request):
    rooms = Rooms.objects.filter(room_owner=request.user)
    advancebooking = AdvanceBooking.objects.get(manager_id=request.user)
    context={'rooms':rooms,'adv_days':advancebooking}
    return render(request,'manager/manager.html',context)

@login_required
@role_required(allowed=['manager'])
def createRoom(request):
    user = request.user
    form = RoomForm()
    if request.method=="POST":
        form = RoomForm(request.POST)
        form.instance.room_owner = user
        try:
            temp = form.save(commit=False)
            temp.room_name=temp.room_name.title()
            t1 = temp.id
            temp.save()
            return redirect(f'time-slot/{t1}')
        except:
            messages.error(request,"Room Already Exist!")
            return HttpResponseRedirect(request.path_info)
    context={'form':form,'user':user}
    return render(request,'manager/create_room.html',context)

@login_required
@role_required(allowed=['manager'])
def deleteRoom(request,pk):
    room = Rooms.objects.get(id=pk)
    if request.method == "POST":
        room.delete()
        messages.add_message(request,messages.SUCCESS,f"Room Deleted Successfully ")

    return redirect('manager')

@login_required
@role_required(allowed=['manager'])
def addTimeSlot(request,pk):
    user = request.user
    form = TimeSlotForm()
    room_name = Rooms.objects.get(id=pk)
    if request.method=="POST":
        form = TimeSlotForm(request.POST)
        form.instance.slot_owner = user
        form.instance.room_id = Rooms.objects.get(id=pk)
        temp = form.save(commit=False)
        ts = TimeSlot.objects.filter(room_id=pk)
        client = [str(temp.start_time),str(temp.end_time)]
        print("Client :",client)
        flag=True
        msg = "Time Slot Added Successfully"
        if client[0]>client[1]:
            messages.warning(request,"Start time cannot exceed end time!")
        else:
            for i in ts:
                check=list(str(i).split('-'))
                if client[0]==check[0] and client[1]==check[1]:
                    flag=False
                    msg = "Time Slot Already Added"
                    break
                elif check[0]<client[0]<check[1] or check[0]<client[1]<check[1]:
                    flag=False
                    msg = f"Time slot {'-'.join(client)} clashes with {i}"
                    break
            if flag:
                temp.save()
                messages.success(request,msg)
            else:
                messages.warning(request,msg)

        return redirect(request.path_info)


    ts = TimeSlot.objects.filter(slot_owner=request.user,
                                  room_id=Rooms.objects.get(id=pk))
    context={'form':form , 'ts':ts,'room_name':room_name}
    return render(request,'manager/add_time_slot.html',context)

@login_required
@role_required(allowed=['manager'])
def editAdvanceDays(request):
    if request.method == "POST":
        days = request.POST["adv_days"]
        user = AdvanceBooking.objects.get(manager_id=request.user)
        user.no_of_days = days
        user.save()
        messages.add_message(request,messages.SUCCESS,'Updated Advance Booking Days')
        return redirect('manager')
    else:
        messages.add_message(request, messages.ERROR, 'Login As Manager.')
        logout(request)
        return redirect("loginPage")

@login_required
@role_required(allowed=['manager'])
def deleteTimeSlot(request,pk1,pk2):
    if request.method=="POST":
        ts = TimeSlot.objects.get(id=request.POST.get('slot_id'))
        ts.delete()
        messages.add_message(request,messages.SUCCESS,f"Slot Deleted Successfully ")

    return redirect('manager')
@login_required
@role_required(allowed=['manager'])
def bookingHistory(request):
    tsb = TimeSlotBook.objects.filter(manager_id=request.user)
    tsc = TimeSlotCancel.objects.filter(manager_id=request.user)
    context={'bookings':tsb,'cancel':tsc}
    return render(request,'manager/booking_history.html',context)

main/manager/templates/manager/add_time_slot.html
{% extends 'basic.html' %}

{%block content%}
<div class="container d-flex justify-content-center">
    <div class="w-50 border rounded shadow p-4">
        <h1>Add Time Slot</h1>
        <div>

            <form method="POST" action="">
                {% csrf_token %}


                <div class="d-flex align-items-center mb-3">
                    <label class="form-label me-3">Room Owner </label>

                    <input class="form-control w-auto" type="text" name="room_owner" value="{{user.username}}"
                           disabled/>

                </div>
                <div class="d-flex align-items-center mb-3">
                    <label class="form-label me-3">Room Name </label>


                    <input class="form-control w-auto" type="text" name="room_name" value="{{room_name}}" disabled/>


                </div>
                <div class="d-flex mb-3">
                   <div class="d-flex align-items-center me-3">
                        <label class="form-label me-3">Start Time</label>
                    <input class="form-control w-auto" type="time" name="start_time" value="12:00" required/>
                   </div>
                   <div class="d-flex align-items-center">
                        <label class="form-label me-3">End Time</label>
                    <input class="form-control w-auto" type="time" name="end_time" value="15:00" required/>
                   </div>
                </div>
                <input type="submit" class="btn btn-dark mb-3" value="Add Time Slot"> </input>
            </form>

        </div>
        <h4> List Of Time Slots </h4>
        {% if ts %}
        <table class="table">
            <thread>
                <tr>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Delete</th>
                </tr>
            </thread>
            <tbody>
            {% for x in ts %}
            <tr>
                <td>{{x.start_time | time:'H:i'}}</td>
                <td>{{x.end_time | time:'H:i'}}</td>
                <td>
                    <form action="{% url 'delete_slot' x.room_id.id x.id %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="slot_id" value="{{x.id}}"> </input>
                        <input type="hidden" name="start_time" value="{{x.start_time | time:'H:i'}}"> </input>
                        <input type="hidden" name="end_time" value="{{x.end_time | time:'H:i'}}"> </input>
                        <input type="hidden" name="end_time" value="{{x.end_time | time:'H:i'}}"> </input>
                        <input type="submit" class="btn btn-outline-dark" value="Delete">
                    </form>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
        <br>
        <p>No Time Slot Available.</p>
        {% endif %}


    </div>
</div>

{%endblock content%}

main/manager/templates/manager/booking_history.html
{% extends 'basic.html' %}

{%block content%}
<div>
    <h3>Upcoming Appointments</h3>

    <div>
        {% if bookings %}
        <table class="table">
            <thred>
                <tr>
                    <td>No.</td>
                    <td>Client Name</td>
                    <td>Phone Number </td>
                    <td>Email</td>
                    <td>Date</td>
                    <td>Room Name</td>
                    <td>Start Time</td>
                    <td>End Time</td>
                </tr>
            </thred>
            <tbody>
                {% for x in bookings %}
                <tr>
                    <td>{{forloop.counter}} </td>
                    <td><p><button class="btn btn-primary btn-sm p-0 px-1 rounded-pill fw-bold" disabled>{{x.client_id.first_name}} {{x.client_id.last_name}}</button></p></td>
                    <td>{{x.client_id.phone}}</td>
                    <td>{{x.client_id.email}}</td>
                    <td>{{x.date}}</td>
                    <td>{{x.room_id}}</td>
                    <td>{{x.start_time | time:"H:i"}}</td>
                    <td>{{x.end_time | time:"H:i"}}</td>
                <tr/>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p> No upcoming bookings made yet </p>
        {% endif %}
    </div>

     <div>
        {% if cancel %}
         <h3> Canceled Bookings</h3>
        <table class="table">
            <thred>
                <tr>
                    <td>No.</td>
                    <td>Client Name</td>
                    <td>Phone Number </td>
                    <td>Email</td>
                    <td>Date</td>
                    <td>Room Name</td>
                    <td>Start Time</td>
                    <td>End Time</td>
                </tr>
            </thred>
            <tbody>
                {% for x in cancel %}
                <tr>
                    <td>{{forloop.counter}} </td>
                    <td><p><button class="btn btn-primary btn-sm p-0 px-1 rounded-pill fw-bold" disabled>{{x.client_id.first_name}} {{x.client_id.last_name}}</button></p></td>
                    <td>{{x.client_id.phone}}</td>
                    <td>{{x.client_id.email}}</td>
                    <td>{{x.date}}</td>
                    <td>{{x.room_id}}</td>
                    <td>{{x.start_time | time:"H:i"}}</td>
                    <td>{{x.end_time | time:"H:i"}}</td>
                <tr/>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>

</div>

{% endblock content%}

main/manager/templates/manager/create_room.html
{% extends 'basic.html' %}

{%block content%}
<div>
    <div class="container d-flex justify-content-center">

        <div class="w-50 shadow border rounded p-4">
            <h3>Add room</h3>

        <form method="POST" action="">
            {% csrf_token %}
                <label class="form-label mb-2">Room Owner </label>
                <input class="form-control mb-2" type="text" name="room_owner" value="{{user.username}}" disabled> </input>
                <p><label class="form-label mb-2" for="id_room_name">Room name</label> <input class="form-control mb-2" type="text" name="room_name" maxlength="10" required id="id_room_name"></p>
            <input class="btn btn-dark" type="submit" value="Add Room">
        </form>

    </div>
    </div>

</div>

{%endblock content%}

main/manager/templates/manager/manager.html
{% extends 'basic.html' %}

{%block content%}
<div class="container d-flex justify-content-center">
    <div class="w-50 border shadow p-4 rounded-3">
        <h1> Manager Page</h1>
        <div>
            <form method="POST" action="{% url 'advance_days' %}">
                {% csrf_token %}
                <div>
                    <Label class="form-label">No. of days to Book in Advance </Label>

                    <div class="row gx-3 w-75">
                        <div class="col-10 ">
                            <input class="col form-control" type="text" name="adv_days" value="{{adv_days.no_of_days}}"
                                   required>
                        </div>
                        <div class="col-2">
                            <input class="col form-control btn btn-outline-dark" type="submit" value="Edit">

                        </div>
                    </div>
                </div>
            </form>
            <div>
                <a href="{% url 'create_room'%}" class="btn btn-dark mt-3"> Create Room </a>
            </div>
            {%if rooms %}
            <table class="table w-50 mt-3">
                <thread>
                    <tr>
                        <th>Room Name</th>
                        <th colspan="2" class="text-center"> </th>
                    </tr>
                </thread>

                <tbody class="border-0">
                {% for room in rooms %}
                <tr class="border-0">
                    <td class="border-0">
                        <Label>{{room.room_name}}</Label>
                    </td>
                    <td class="d-flex justify-content-end border-0">
                        <form action="{% url 'time_slot' room.id%}" class="me-3">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-dark" value="Edit"> </input>
                        </form>
                        <form action="{% url 'delete_room' room.pk %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-outline-dark" value="Delete"> </input>
                        </form>
                    </td>
                    {% endfor %}
                </tr>
                </tbody>
            </table>
            {% endif %}
            <a href="{% url 'bookings' %}">
                <button class="btn btn-outline-dark">Bookings</button>
            </a>
        </div>

    </div>
</div>

{%endblock content%}